---
deployment:
  tasks:
    # Deploy para o subdomínio imersao.dinamicasul.com.br (usuário cPanel: dinamic1)
    - export DEPLOYPATH=/home/dinamic1/public_html/imersao/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R imagens $DEPLOYPATH
    - /bin/cp -R obrigado $DEPLOYPATH
